# Generated by Django 5.1 on 2024-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_acc_id_accomodation_accomodation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='packagereview',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packagereview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
