# Generated by Django 5.1 on 2024-09-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_accomodation_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
