# Generated by Django 5.1 on 2024-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/accommodation_images/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/destination_images/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/package_images/'),
        ),
    ]
